### ISSUE TITLE
[BUG] - AC-WotLK: Reputation changes after logout (fix included)

### ISSUE THREAD

**Issue by yani9o** [Aldori15/azerothcore-eluna-accountwide#5]
**Describe the bug**
Everytime a character logs out some reputations get changed.
For example (nightelf):
faction 930 = -100 rep
faction 1090 = -3000 rep

**To Reproduce**
1. Fresh install of AzerothCore (Docker), mod-eluna and AccountReputation.lua
2. Create character
3. Login
4. Logout
5. check character_reputations table in database

**Expected behavior**
no additional changes when logging out / all factions should be at 0 (for newly created characters)

**Additional context**
seems like the standard-values in baseReputationValues{} are off (at least for azerothcore-wotlk).
fixed all races and they stay like they should now and removed non-wotlk races (replace the content of AccountReputation.lua with this):
[AccountReputation.txt](https://github.com/user-attachments/files/17631357/AccountReputation.txt)
had to add faction 1082 to all horde races (no idea what faction that is, wowhead says "REUSE" and added in 3.4.0), kept giving me -42000 rep at logout (didn't add it to hordeFactions{} tho)

**Comment by Aldori15** [comment]
Maybe what i'll do is include two versions of the AccountReputation script on this repo - mine (modified for Ashen Order server with the custom races+Faction.dbc values) and yours (standard AC-Wotlk)

**Comment by Aldori15** [comment]
@yani9o I uploaded both versions of the AccountReputation script and also updated the ReadMe instructions.
